<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHj4EXeF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHj4EXeF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHj4EXeF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHj4EXeF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHj4EXeF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hj4EXeF',
    'container.build_id' => '6247ef48',
    'container.build_time' => 1584806260,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHj4EXeF');
